extends SceneTree

const RepairSimulationScript := preload("res://scripts/repair_simulation.gd")
const WardrobeSimulationScript := preload("res://scripts/wardrobe_simulation.gd")
const PortalMirrorHouseScript := preload("res://scripts/portal_mirror_house.gd")
const PortalMirrorSimulationScript := preload("res://scripts/portal_mirror_simulation.gd")
const GargoyleSimulationScript := preload("res://scripts/gargoyle_simulation.gd")
const EmployeeReactionResolverScript := preload("res://scripts/employee_reaction_resolver.gd")
const RepairHUDScript := preload("res://scripts/repair_hud.gd")

var failures := PackedStringArray()


func _initialize() -> void:
	var lava: RefCounted = RepairSimulationScript.new()
	var flowing_heat_line: String = lava.get_employee_reaction(&"liliya", &"heat")
	_check("опечатки" in flowing_heat_line, "Лилия комментирует нагрев текущей лавы до действия")
	_check("уберите лаву" in lava.get_employee_reaction(&"boris", &"repair"), "Борис предупреждает о текущей лаве")
	var diagnosis: String = str(lava.apply_action(&"boris", &"diagnose").get("message", ""))
	_check("давлен" not in diagnosis.to_lower() and "температура 9" not in diagnosis.to_lower(), "Осмотр крана описывает состояние без внутренних чисел и давления")
	lava.apply_action(&"liliya", &"freeze")
	_check("уплотнения" in lava.get_employee_reaction(&"boris", &"repair"), "После остановки лавы Борис не повторяет устаревшее предупреждение")
	var frozen_heat_line: String = lava.get_employee_reaction(&"liliya", &"heat")
	_check("застывшая лава снова пойдёт" in frozen_heat_line and frozen_heat_line != flowing_heat_line, "После заморозки Лилия предупреждает о таянии ледяной пробки")
	var thaw_result: Dictionary = lava.apply_action(&"liliya", &"heat")
	_check("снова течёт" in str(thaw_result.get("message", "")) and not bool(thaw_result.get("resolved", true)), "Нагрев замёрзшего крана возобновляет аварию")
	_check((lava.world_object["tags"] as PackedStringArray).has("lava_flowing") and not bool(lava.world_object["frozen"]), "После таяния пробки поток лавы восстановлен, а холодный след снят")
	lava.apply_action(&"liliya", &"freeze")
	_check("давлен" not in str(lava.get_completion_result().get("summary", "")).to_lower(), "Акт по лавовому крану не упоминает скрытое давление")
	var melted_faucet: RefCounted = RepairSimulationScript.new()
	melted_faucet.apply_action(&"liliya", &"heat")
	melted_faucet.apply_action(&"liliya", &"heat")
	_check("услуги по сносу" in str(melted_faucet.get_completion_result().get("review", "")), "Рагнар осуждает уничтожение крана без положительной оговорки")

	var wardrobe: RefCounted = WardrobeSimulationScript.new()
	var left_line: String = wardrobe.get_employee_reaction(&"grog", &"physical_move", &"move_left")
	var kitchen_line: String = wardrobe.get_employee_reaction(&"grog", &"physical_move", &"move_kitchen")
	_check("левой стене" in left_line, "Грог называет выбранную левую стену")
	_check("кухню" in kitchen_line and kitchen_line != left_line, "Для прохода на кухню у Грога отдельная реплика")
	var antimagic_only_wardrobe: RefCounted = WardrobeSimulationScript.new()
	var antimagic_only_result: Dictionary = antimagic_only_wardrobe.apply_action(&"felix", &"antimagic")
	var antimagic_only_report: Dictionary = antimagic_only_wardrobe.get_completion_result()
	_check(bool(antimagic_only_result["resolved"]) and antimagic_only_wardrobe.world_object["position_zone"] == &"entrance", "Антимагия Феликса завершает заявку без обязательного перемещения шкафа")
	_check(int(antimagic_only_report["reward_adjustment"]) < 0 and "не там" in str(antimagic_only_report["summary"]), "Акт учитывает шкаф, оставленный не в заказанном месте")

	var portal: RefCounted = PortalMirrorSimulationScript.new()
	var portal_room := PortalMirrorHouseScript.new()
	_check(portal_room._is_instant_physical_action(&"physical_move"), "Грог разбивает зеркало сразу без двухминутной работы")
	_check(portal_room._should_show_resident_damage_reaction(&"physical_move", {"applied": true}, 0, 10, "Это было фамильное зеркало!"), "После удара Грога показывается реакция хозяйки на уничтожение зеркала")
	portal_room.free()
	_check("Семь лет" in portal.get_employee_reaction(&"grog", &"physical_move"), "Грог предупреждает о разбивании зеркала")
	portal.apply_action(&"grog", &"physical_move")
	_check("фамильное зеркало" in portal.get_resident_reaction(&"physical_move"), "У хозяйки есть отдельная реплика на разбитое зеркало")
	_check(bool(portal.get_completion_result().get("forfeit_payment", false)), "Уничтоженное зеркало полностью лишает службу оплаты")
	portal = PortalMirrorSimulationScript.new()
	var missing_cloth: Dictionary = portal.apply_action(&"boris", &"cover", false)
	_check(not bool(missing_cloth["applied"]) and "лавке снабжения" in str(missing_cloth["message"]), "Без купленного полотна Борис не закрывает зеркало")
	portal.apply_action(&"liliya", &"heat")
	_check(int(portal.world_object["damage"]) == 0, "Первый нагрев только убирает холод и не штрафует за раму")
	portal.apply_action(&"liliya", &"heat")
	portal.apply_action(&"boris", &"cover")
	var damaged_cover_result: Dictionary = portal.get_completion_result()
	_check(portal.visual_state() == &"covered_heat_damaged", "Оплавленная рама с полотном использует отдельный визуальный вариант")
	_check(int(damaged_cover_result["reward_adjustment"]) == -430, "Оплавленная рама сразу снижает оплату на 350 монет поверх штрафа за полотно")
	_check(int(damaged_cover_result["expense_reimbursement"]) == 50, "Стоимость использованного полотна включается в оплату")
	_check(int(damaged_cover_result["reputation_change"]) == -2, "Оплавленная рама под полотном снижает репутацию на 2")
	_check("деформирована" in str(damaged_cover_result["summary"]), "Акт с полотном указывает повреждение рамы")
	var closed_damaged_portal: RefCounted = PortalMirrorSimulationScript.new()
	closed_damaged_portal.apply_action(&"liliya", &"heat")
	closed_damaged_portal.apply_action(&"liliya", &"heat")
	var repeated_heat: Dictionary = closed_damaged_portal.apply_action(&"liliya", &"heat")
	_check(int(closed_damaged_portal.world_object["damage"]) == 1, "Повторный нагрев не создаёт скрытые степени повреждения")
	_check("состояние заметно не изменилось" in str(repeated_heat["message"]), "Повторный нагрев явно сообщает, что нового события для реакции хозяйки нет")
	closed_damaged_portal.apply_action(&"felix", &"antimagic")
	var damaged_closed_result: Dictionary = closed_damaged_portal.get_completion_result()
	_check(closed_damaged_portal.visual_state() == &"closed_heat_damaged", "Закрытый портал сохраняет оплавленный вид рамы")
	_check(int(damaged_closed_result["reward_adjustment"]) == -350 and "деформированной" in str(damaged_closed_result["summary"]), "Акт закрытого портала сразу снимает 350 монет за оплавленную раму")
	_check(int(damaged_closed_result["reputation_change"]) == -1, "Закрытый портал с оплавленной рамой снижает репутацию на 1")
	var repeated_close: Dictionary = closed_damaged_portal.apply_action(&"felix", &"antimagic")
	_check(not bool(repeated_close["applied"]), "Повторное закрытие уже закрытого портала не применяется")
	var covered_then_closed: RefCounted = PortalMirrorSimulationScript.new()
	covered_then_closed.apply_action(&"liliya", &"heat")
	covered_then_closed.apply_action(&"liliya", &"heat")
	covered_then_closed.apply_action(&"boris", &"cover")
	var blocked_close: Dictionary = covered_then_closed.apply_action(&"felix", &"antimagic")
	_check(not bool(blocked_close["applied"]) and bool(covered_then_closed.world_object["portal_open"]), "Феликс не закрывает портал сквозь защитное полотно")
	_check(bool(covered_then_closed.apply_action(&"boris", &"uncover")["applied"]), "Борис может снять защитное полотно")
	_check(covered_then_closed.visual_state() == &"heat_damaged", "После снятия полотна снова видна оплавленная открытая рама")
	_check(bool(covered_then_closed.apply_action(&"felix", &"antimagic")["applied"]), "После снятия полотна Феликс закрывает портал")
	_check(covered_then_closed.visual_state() == &"closed_heat_damaged" and not bool(covered_then_closed.world_object["covered"]), "После закрытия показывается оплавленная рама без полотна")
	_check(not str(covered_then_closed.get_completion_result()["summary"]).contains("полотн"), "Акт после окончательного закрытия не считает зеркало завешенным")
	var portal_scene := (load("res://scenes/PortalMirrorHouse.tscn") as PackedScene).instantiate()
	_check(portal_scene.has_node("PortalMirror/ClosedHeatDamaged") and portal_scene.has_node("PortalMirror/CoveredHeatDamaged"), "Оба новых состояния зеркала подключены к сцене")
	portal_scene.free()

	var gargoyle: RefCounted = GargoyleSimulationScript.new()
	_check("разговаривать будете вы" in gargoyle.get_employee_reaction(&"liliya", &"heat"), "Лилия произносит согласованную реплику перед нагревом горгульи")
	_check(not EmployeeReactionResolverScript.no_effect_for(&"nika").is_empty(), "Для неудачного воздействия есть живая реплика сотрудника")

	var repair_hud: Control = RepairHUDScript.new()
	_check(repair_hud.should_show_employee_reaction(&"liliya", "Одна и та же реплика."), "Новая реплика сотрудника показывается")
	_check(not repair_hud.should_show_employee_reaction(&"liliya", "Одна и та же реплика."), "Уже произнесённая реплика сотрудника не повторяется")
	_check(repair_hud.should_show_employee_reaction(&"liliya", "Другая реплика."), "Другая реплика того же сотрудника остаётся доступна")
	repair_hud.free()

	if failures.is_empty():
		print("ACTION DIALOGUE SMOKE TEST: PASS")
		quit(0)
	else:
		print("ACTION DIALOGUE SMOKE TEST: FAIL (%d)" % failures.size())
		quit(1)


func _check(condition: bool, message: String) -> void:
	if condition:
		print("PASS: ", message)
	else:
		failures.append(message)
		push_error("FAIL: %s" % message)
