extends SceneTree

const Generator := preload("res://scripts/generated_job_generator.gd")
const Simulation := preload("res://scripts/frozen_bath_simulation.gd")
const Memory := preload("res://scripts/world_memory.gd")
var failures: Array[String] = []

func _initialize() -> void:
	call_deferred("_run")

func _check(condition: bool, message: String) -> void:
	if not condition:
		failures.append(message)
		push_error(message)

func _run() -> void:
	var event := {"event_id": "bath.test", "event_type": "cold_trace", "payload": {"anomaly_id": "cold_trace"}}
	var memory := Memory.new()
	memory.reset()
	var instance: Dictionary = Generator.generate_faucet_consequence(event, ["heat"], memory.generator_context())
	_check(not instance.is_empty(), "Cold trace has a solution")
	_check(str(instance.get("simulation_type", "")) == "cold_trace", "Correct simulator selected")
	var job: Dictionary = Generator.materialize_job(instance)
	var sim := Simulation.new()
	sim.initialize_from_job(job)
	_check(bool(sim.world_object["frozen"]) and not bool(sim.world_object["valve_frozen"]), "Frozen surface does not block valve")
	sim.advance_flow_until(540)
	sim.apply_action(&"liliya", &"heat", false, &"bath")
	_check(bool(sim.world_object["ice_removed"]) and not sim.is_resolved(), "Bath cleared without resolving source")
	sim.advance_flow_until(541)
	_check(not bool(sim.world_object["ice_removed"]), "Ice flow fills empty bath again")
	sim.apply_action(&"liliya", &"heat", false, &"faucet")
	_check(sim.is_resolved() and bool(sim.world_object["bath_still_frozen"]), "Source resolution permits remaining ice")
	var completion: Dictionary = sim.get_completion_result()
	_check(int(completion["reward_adjustment"]) == -80 and int(completion["compensation_cost"]) == 0, "Existing ice payment retained")
	_check("лёд остался" in str(completion["summary"]), "Act reports remaining ice")
	sim.apply_action(&"liliya", &"heat", false, &"bath")
	sim.advance_flow_until(542)
	_check(bool(sim.world_object["ice_removed"]), "No refill after source removed")
	var damaged := Simulation.new()
	damaged.initialize_from_job(job)
	damaged.apply_action(&"grog", &"physical_move", false, &"bath")
	damaged.apply_action(&"liliya", &"heat", false, &"faucet")
	_check(int(damaged.get_completion_result()["compensation_cost"]) == 180, "Bath compensation retained")
	memory.record_job_state(&"generated_faucet_test", damaged.get_state(), 2, 540)
	_check(bool(memory.objects[Simulation.BATH_INSTANCE_ID]["properties"]["damaged"]), "Bath damage remembered independently")
	var restored := Simulation.new()
	restored.load_state(sim.get_state())
	_check(restored.is_fully_resolved(), "State roundtrip")
	var old_memory := Memory.new()
	old_memory.reset()
	old_memory.queue_consequence(&"thermal_instability", &"faucet_freeze", "old_quarter_5.bathroom.lava_faucet", &"test_source", 2, 540, 80, {"anomaly_id": "faucet_freeze"}, "old_chain", "", 1)
	var migrated := Memory.new()
	migrated.load_data(old_memory.to_data())
	_check(migrated.has_consequence(&"cold_trace") and str(migrated.deferred_events[0]["cause_chain_id"]) == "old_chain", "Pending cold trace migration preserves cause")
	var closed := Simulation.new()
	closed.initialize_from_job(job)
	closed.advance_flow_until(540)
	closed.apply_action(&"boris", &"turn_valve", false, &"faucet")
	closed.apply_action(&"liliya", &"heat", false, &"bath")
	closed.advance_flow_until(541)
	_check(bool(closed.world_object["ice_removed"]) and not closed.is_resolved(), "Closed valve stops refill but does not remove trace")
	closed.apply_action(&"boris", &"turn_valve", false, &"faucet")
	closed.advance_flow_until(542)
	_check(not bool(closed.world_object["ice_removed"]), "Opening valve resumes ice flow")
	var state = root.get_node("GameState")
	state.start_new_game()
	instance["instance_id"] = "generated_faucet_bath_test"
	state._register_generated_job(instance)
	state.active_job_id = &"generated_faucet_bath_test"
	state.set_job_repair_state(state.active_job_id, damaged.get_state())
	_check(state._save_to_path("res://tests/.cold_trace_roundtrip.json") == OK, "Campaign saved")
	_check(state._load_from_path("res://tests/.cold_trace_roundtrip.json") == OK, "Campaign loaded")
	_check(str(state.jobs[&"generated_faucet_bath_test"]["simulation_type"]) == "cold_trace", "Saved scene adapter retained")
	state.active_job_id = &"generated_faucet_bath_test"
	state.set_job_repair_state(state.active_job_id, {})
	var room = load("res://scenes/FrozenBathRoom.tscn").instantiate()
	root.add_child(room)
	await process_frame
	_check(room.frozen_bath.visible and not room.normal_faucet.visible and room.frozen_faucet.visible, "Frozen faucet and ice bath assets connected")
	_check(room.ice_motion != null and room.ice_motion.is_running(), "Ice uses Godot motion")
	_check(room.ice_stream.visible and room.ice_stream.texture != null, "Provided ice stream connected")
	room.ice_stream.position = Vector2(340, 430)
	room.ice_stream.size = Vector2(110, 180)
	room._apply_visual_state()
	_check(room.ice_stream.position == Vector2(340, 430) and room.ice_stream.size == Vector2(110, 180), "Editor geometry is not overwritten")
	room.simulation.apply_action(&"liliya", &"heat", false, &"faucet")
	room._apply_visual_state()
	_check(room.frozen_bath.visible, "Removing trace leaves bath visual intact")
	_check(not room.ice_stream.visible, "Removing source hides stream")
	_check(not room.ice_motion.is_running(), "Hidden ice motion paused")
	_check(room.normal_faucet.visible and not room.frozen_faucet.visible, "Source removed restores normal faucet")
	room.simulation.apply_action(&"liliya", &"heat", false, &"bath")
	room._apply_visual_state()
	_check(not room.frozen_bath.visible, "Clearing bath hides ice asset")
	room.queue_free()
	await process_frame
	if failures.is_empty():
		print("Cold trace bath smoke test: PASS")
	quit(0 if failures.is_empty() else 1)
