extends SceneTree

const FrozenBathSimulationScript := preload("res://scripts/frozen_bath_simulation.gd")
const RepairSimulationScript := preload("res://scripts/repair_simulation.gd")

var failures := PackedStringArray()


func _initialize() -> void:
	call_deferred("_run")


func _run() -> void:
	var game_state := root.get_node("GameState")
	game_state.start_new_game()
	_check(not game_state._is_valid_pending_report({"claim_status": "none"}), "Пустая устаревшая запись не считается актом выполненных работ")
	_check(game_state.SUPPLY_ITEMS.has(&"thermal_regulator"), "Рунический терморегулятор добавлен в снаряжение")
	_check(not game_state.jobs[&"frozen_bath"]["unlocked"], "Заявка о замёрзшей ванне изначально скрыта")

	var source := RepairSimulationScript.new()
	source.apply_action(&"liliya", &"freeze")
	var source_result: Dictionary = source.get_completion_result()
	_check(str(source_result.get("follow_up", {}).get("type", "")) == "frozen_bath", "Заморозка лавового крана создаёт продолжение")
	var melted_source := RepairSimulationScript.new()
	melted_source.apply_action(&"liliya", &"heat")
	melted_source.apply_action(&"liliya", &"heat")
	_check(bool(melted_source.get_completion_result().get("forfeit_payment", false)), "За уничтоженный лавовый кран служба не получает оплату")
	var restored_bath := FrozenBathSimulationScript.new()
	restored_bath.load_state({"world_object": {"resident_intro_seen": true}, "action_log": [{"employee_id": "boris", "action_id": "diagnose", "result": {}}]})
	_check(restored_bath.action_log.size() == 1 and bool(restored_bath.world_object["resident_intro_seen"]), "Состояние ванной и журнал действий безопасно загружаются из сохранения")
	game_state.completed_job_ids = PackedStringArray(["lava_leak"])
	game_state.job_reports = [{"job_id": "lava_leak", "completed_day": 1, "follow_up": source_result["follow_up"]}]
	game_state.day = 2
	game_state._unlock_frozen_bath_job_if_due()
	game_state._update_parallel_job_unlocks()
	_check(game_state.is_job_available(&"frozen_bath"), "На следующий день открывается заявка о ванной")
	_check(game_state.is_job_available(&"walking_wardrobe") and not game_state.is_job_available(&"portal_mirror"), "При заявке-последствии второй день содержит только ванну и шкаф")
	game_state.day = 3
	game_state._update_parallel_job_unlocks()
	game_state.completed_job_ids.append("walking_wardrobe")
	game_state._unlock_gargoyle_job_if_due()
	_check(game_state.is_job_available(&"portal_mirror"), "Отложенная заявка с порталом открывается на третий день")
	_check(game_state.is_job_available(&"sleeping_gargoyle"), "Горгулья открывается в тот же день, что и отложенный портал")

	var scene := load("res://scenes/FrozenBathRoom.tscn") as PackedScene
	_check(scene != null, "Сцена замёрзшей ванной загружается")
	_check(load("res://assets/objects/frozen_bath/bath_frozen.png") != null and load("res://assets/objects/frozen_bath/bath_broken_empty.png") != null and load("res://assets/objects/frozen_bath/faucet_frozen.png") != null, "Переданные состояния ванны и крана импортированы")
	var room := scene.instantiate()
	var faucet := room.get_node("Faucet") as Control
	var source_scene := (load("res://scenes/RepairHouse.tscn") as PackedScene).instantiate()
	var source_faucet := source_scene.get_node("InteractiveObjects/LavaFaucet") as Control
	_check(faucet.position == source_faucet.position and faucet.size == source_faucet.size, "Кран использует размер и положение первой заявки")
	_check((room.get_node("FrozenBath") as TextureRect).size.x > 0.0 and (room.get_node("FrozenBath") as TextureRect).size.y > 0.0, "Ванна подключена отдельным настраиваемым слоем")
	_check((room.get_node("BrokenEmptyBath") as TextureRect).size.x > 0.0 and (room.get_node("BrokenEmptyBath") as TextureRect).size.y > 0.0, "Пустое разбитое состояние ванны имеет настроенную область отображения")
	_check(room.has_node("Faucet/FrostOverlay"), "На повторно замерзающий кран добавлен отдельный слой инея")
	_check(room.has_node("FaucetInteractionButton") and room.has_node("BathInteractionButton"), "Кран и ванна имеют отдельные области выбора")
	_check((room.get_node("FaucetTarget") as Marker2D).position != (room.get_node("BathTarget") as Marker2D).position, "Заклинания направляются в разные точки крана и ванны")
	_check(room._hidden_actions_for_target(&"faucet").has("telekinesis"), "Телекинез Ники скрыт при выборе крана")
	_check(not room._hidden_actions_for_target(&"bath").has("telekinesis"), "Телекинез Ники доступен при выборе ванны")
	_check(not room._hidden_actions_for_target(&"faucet").has("heat") and not room._hidden_actions_for_target(&"bath").has("freeze"), "Огонь и заморозка Лилии доступны на обеих целях")
	_check(not room._employee_has_action_for_target(PackedStringArray(["telekinesis"]), &"faucet"), "Нажатие Никой на кран не открывает пустую панель действий")
	_check(not room._employee_has_action_for_target(PackedStringArray(["antimagic"]), &"bath"), "Нажатие Феликсом на ванну не открывает пустую панель действий")
	_check("не стану" in room._target_refusal_for_employee(&"nika", &"faucet") and "на кране" in room._target_refusal_for_employee(&"felix", &"bath"), "Для неподходящих целей сотрудники дают понятные объяснения")
	_check("Кран тоже могу расколоть" in room._target_refusal_for_employee(&"grog", &"faucet"), "Грог с юмором отказывается ломать кран")
	_check("одним куском" in room._instant_target_result(&"boris", &"bath") and room._instant_target_result(&"boris", &"faucet").is_empty(), "При выборе ванны Борис сразу сообщает результат без повторного осмотра")
	_check(room.has_node("PauseMenu") and not bool(room.get_node("PauseMenu").show_default_menu_button), "Esc-меню подключено без отдельной кнопки")
	room.free()
	source_scene.free()

	var heat_route := FrozenBathSimulationScript.new()
	_check(bool(heat_route.apply_action(&"liliya", &"heat")["resolved"]), "Магия огня устраняет замерзание")
	var split_heat_route := FrozenBathSimulationScript.new()
	var bath_heat: Dictionary = split_heat_route.apply_action(&"liliya", &"heat", false, &"bath")
	_check(bool(bath_heat["applied"]) and bool(split_heat_route.world_object["ice_removed"]) and not split_heat_route.is_resolved(), "Огонь по ванне растапливает лёд, но не снимает след с крана")
	var faucet_heat: Dictionary = split_heat_route.apply_action(&"liliya", &"heat", false, &"faucet")
	_check(bool(faucet_heat["applied"]) and split_heat_route.is_fully_resolved(), "Отдельный огонь по крану снимает холодный след и завершает работу")
	_check(not bool(split_heat_route.apply_action(&"liliya", &"heat", false, &"faucet")["applied"]), "Лилия повторно не нагревает уже очищенный кран")
	var antimagic_route := FrozenBathSimulationScript.new()
	_check(bool(antimagic_route.apply_action(&"nika", &"antimagic")["resolved"]), "Антимагия устраняет холодный след")
	_check(bool(antimagic_route.world_object["bath_still_frozen"]), "После антимагии лёд остаётся в ванне")
	_check(int(antimagic_route.get_completion_result()["reward_adjustment"]) < 0, "За оставшийся лёд жилец снижает оплату")
	_check(not antimagic_route.is_fully_resolved(), "После антимагии с ванной ещё можно взаимодействовать")
	antimagic_route.apply_action(&"liliya", &"heat")
	_check(antimagic_route.is_fully_resolved() and int(antimagic_route.get_completion_result()["reward_adjustment"]) == 0, "После антимагии лёд можно растопить и получить полную оплату")
	var regulator_route := FrozenBathSimulationScript.new()
	_check(not bool(regulator_route.apply_action(&"nika", &"install_regulator", false)["applied"]), "Без покупки регулятор установить нельзя")
	_check(bool(regulator_route.apply_action(&"nika", &"install_regulator", true)["resolved"]), "Купленный регулятор решает заявку")
	_check(not regulator_route.is_fully_resolved(), "Регулятор останавливает замерзание, но не растапливает ванну")
	_check(int(regulator_route.get_completion_result()["expense_reimbursement"]) == 280, "Стоимость установленного терморегулятора включается в оплату")
	regulator_route.apply_action(&"nika", &"telekinesis")
	_check(regulator_route.is_fully_resolved() and bool(regulator_route.world_object["ice_removed"]), "Ника убирает лёд из целой ванны и полностью завершает работу")
	var cleared_then_antimagic := FrozenBathSimulationScript.new()
	cleared_then_antimagic.apply_action(&"nika", &"telekinesis")
	var cleared_reaction := cleared_then_antimagic.get_employee_reaction(&"felix", &"antimagic")
	var cleared_result: Dictionary = cleared_then_antimagic.apply_action(&"felix", &"antimagic")
	var cleared_report: Dictionary = cleared_then_antimagic.get_completion_result()
	_check("уже убран" in cleared_reaction.to_lower(), "Феликс учитывает, что Ника уже убрала лёд")
	_check(not "лёд в ванне остался" in str(cleared_result["message"]).to_lower() and cleared_then_antimagic.is_fully_resolved(), "Результат антимагии не возвращает отсутствующий лёд")
	_check(not "лёд остался" in str(cleared_report["summary"]).to_lower() and int(cleared_report["reward_adjustment"]) == 0, "Итог заявки после телекинеза и антимагии считается полным")
	var repeated_antimagic_route := FrozenBathSimulationScript.new()
	repeated_antimagic_route.apply_action(&"felix", &"antimagic")
	var repeated_antimagic: Dictionary = repeated_antimagic_route.apply_action(&"felix", &"antimagic")
	_check(not bool(repeated_antimagic["applied"]) and "уже снят" in str(repeated_antimagic["message"]), "Феликс повторно не снимает уже устранённый холодный след")
	var repeated_telekinesis_route := FrozenBathSimulationScript.new()
	repeated_telekinesis_route.apply_action(&"nika", &"telekinesis")
	var repeated_telekinesis: Dictionary = repeated_telekinesis_route.apply_action(&"nika", &"telekinesis")
	_check(not bool(repeated_telekinesis["applied"]) and "уже убран" in str(repeated_telekinesis["message"]), "Ника повторно не убирает отсутствующий лёд")
	var boris_route := FrozenBathSimulationScript.new()
	_check("терморегулятор" in str(boris_route.apply_action(&"boris", &"diagnose")["message"]).to_lower() and "холодное отношение" in boris_route.get_employee_reaction(&"boris", &"diagnose"), "Осмотр Бориса имеет личную реплику и отдельный системный вывод для повторной проверки")
	_check(bool(boris_route.world_object["faucet_diagnosed"]), "Первый осмотр крана сохраняется и не требует повторной траты времени")
	_check("воду теперь можно вынимать отсюда одним куском" in boris_route.get_employee_reaction(&"boris", &"diagnose", &"bath"), "При осмотре ванны Борис говорит о ванне, а не о кране")
	_check("цельная масса льда" in str(boris_route.apply_action(&"boris", &"diagnose", false, &"bath")["message"]), "Системный результат осмотра ванны описывает ванну, а не кран")
	_check(not bool(boris_route.apply_action(&"boris", &"repair", false)["applied"]), "Борис не устанавливает отсутствующий регулятор")
	_check(bool(boris_route.apply_action(&"boris", &"repair", true)["resolved"]), "После покупки Борис устанавливает регулятор")
	var grog_route := FrozenBathSimulationScript.new()
	var impact: Dictionary = grog_route.apply_action(&"grog", &"physical_move")
	_check(bool(impact["applied"]) and not grog_route.is_resolved(), "Разбитый лёд не устраняет причину")
	_check("молот побольше" in grog_route.get_employee_reaction(&"grog", &"physical_move"), "Грог использует выбранную юмористическую реплику")
	_check(bool(grog_route.apply_action(&"liliya", &"heat")["resolved"]), "После силовой ошибки заявку всё ещё можно завершить")
	_check(bool(grog_route.world_object["bath_damaged"]), "Нагрев и антимагия не чинят разбитую ванну")
	_check(int(grog_route.get_completion_result()["compensation_cost"]) > 0, "Повреждение ванны создаёт претензию")
	_check("ванна треснула" in str(grog_route.get_completion_result()["summary"]).to_lower() and "не устранено" in str(grog_route.get_completion_result()["summary"]).to_lower(), "Акт прямо указывает повреждение ванны и его состояние")
	var broken_antimagic_route := FrozenBathSimulationScript.new()
	broken_antimagic_route.apply_action(&"grog", &"physical_move")
	broken_antimagic_route.apply_action(&"felix", &"antimagic")
	_check(bool(broken_antimagic_route.world_object["bath_damaged"]) and int(broken_antimagic_route.get_completion_result()["compensation_cost"]) > 0, "Антимагия не восстанавливает разбитую Грогом ванну")
	broken_antimagic_route.apply_action(&"nika", &"telekinesis")
	_check(bool(broken_antimagic_route.world_object["ice_removed"]) and bool(broken_antimagic_route.world_object["bath_damaged"]), "Ника убирает лёд, не восстанавливая разбитую ванну")
	var refreeze_route := FrozenBathSimulationScript.new()
	refreeze_route.apply_action(&"liliya", &"freeze")
	_check(not bool(refreeze_route.world_object["ice_removed"]) and not bool(refreeze_route.world_object["cold_trace_removed"]) and bool(refreeze_route.world_object["bath_still_frozen"]) and bool(refreeze_route.world_object["extra_frost"]), "Повторная заморозка возвращает лёд и дополнительный иней на кран")
	var bath_only_freeze_route := FrozenBathSimulationScript.new()
	bath_only_freeze_route.apply_action(&"liliya", &"heat", false, &"faucet")
	bath_only_freeze_route.apply_action(&"liliya", &"freeze", false, &"bath")
	_check(bool(bath_only_freeze_route.world_object["cold_trace_removed"]) and not bool(bath_only_freeze_route.world_object["extra_frost"]), "Заморозка ванны не возвращает иней на очищенный кран")
	var faucet_only_freeze_route := FrozenBathSimulationScript.new()
	faucet_only_freeze_route.apply_action(&"liliya", &"heat", false, &"bath")
	faucet_only_freeze_route.apply_action(&"liliya", &"freeze", false, &"faucet")
	_check(bool(faucet_only_freeze_route.world_object["ice_removed"]) and not bool(faucet_only_freeze_route.world_object["bath_still_frozen"]) and bool(faucet_only_freeze_route.world_object["extra_frost"]), "Заморозка крана не возвращает лёд в ванну")
	_finish()


func _check(condition: bool, message: String) -> void:
	if condition:
		print("PASS: ", message)
	else:
		failures.append(message)
		push_error("FAIL: %s" % message)


func _finish() -> void:
	if failures.is_empty():
		print("FROZEN BATH SMOKE TEST: PASS")
		quit(0)
	else:
		print("FROZEN BATH SMOKE TEST: FAIL (%d)" % failures.size())
		quit(1)
