extends SceneTree

const GargoyleSimulationScript := preload("res://scripts/gargoyle_simulation.gd")

var failures := PackedStringArray()


func _initialize() -> void:
	call_deferred("_run")


func _run() -> void:
	var game_state := root.get_node("GameState")
	game_state.start_new_game()
	_check(not game_state.jobs[&"sleeping_gargoyle"]["unlocked"], "Заявка с горгульей скрыта в первый день")
	game_state.day = 2
	game_state.completed_job_ids = PackedStringArray(["generated_faucet_tutorial_1", "generated_wardrobe_1", "portal_mirror"])
	game_state.job_reports = [
		{"job_id": "lava_leak", "completed_day": 1},
		{"job_id": "generated_wardrobe_1", "completed_day": 2},
		{"job_id": "portal_mirror", "completed_day": 2},
	]
	game_state.advance_day()
	_check(game_state.day == 3, "После заявок второго дня наступает третий день")
	_check(game_state.is_job_available(&"sleeping_gargoyle"), "На третий день открывается заявка с горгульей")
	_check(bool(game_state.jobs[&"sleeping_gargoyle"].get("generated", false)), "Горгулья материализована новым генератором")
	var generator := preload("res://scripts/generated_job_generator.gd")
	_check(not generator.generate_gargoyle(42, PackedStringArray(["repair"])).is_empty(), "Начальная бригада имеет безопасный механический вариант")
	_check(generator.generate_gargoyle(42, PackedStringArray(["physical_move"])).is_empty(), "Генератор не выдаёт заявку с единственным разрушительным решением")
	_check(generator.generate_gargoyle(42, PackedStringArray(["repair"]), {"client_capabilities": {"mirabel": PackedStringArray(["physical_move"])}}).is_empty(), "Запреты клиента учитываются при проверке разрешимости")
	_check(game_state.jobs[&"sleeping_gargoyle"]["repair_scene"] == "res://scenes/GargoyleAttic.tscn", "Заявка ведёт прямо на чердак")
	_check(game_state.jobs[&"sleeping_gargoyle"]["resident_portrait"] == "res://assets/portraits/residents/mirabel.png", "К заявке подключён портрет Мирабель")
	_check(game_state.jobs[&"sleeping_gargoyle"]["resident_portrait_region"] == Rect2(0, 0, 1122, 1402), "Портрет Мирабель использует полный кадр")

	var attic_scene := load("res://scenes/GargoyleAttic.tscn") as PackedScene
	_check(attic_scene != null, "Сцена чердака загружается")
	_check(load("res://assets/backgrounds/gargoyle_attic.png") != null, "Фон чердака загружается")
	_check(load("res://assets/objects/drain_gargoyle/dormant.png") != null, "Спящая горгулья загружается")
	_check(load("res://assets/objects/drain_gargoyle/awakened.png") != null, "Пробуждённая горгулья загружается")
	_check(load("res://assets/objects/drain_gargoyle/damaged.png") != null, "Повреждённая горгулья загружается")
	_check(load("res://assets/objects/drain_gargoyle/damaged_clean.png") != null, "Повреждённая горгулья без листьев загружается")
	_check(load("res://assets/objects/drain_gargoyle/dormant_clean.png") != null, "Очищенная спящая горгулья загружается")
	_check(load("res://assets/objects/drain_gargoyle/frozen.png") != null, "Замёрзшая горгулья загружается")
	_check(load("res://assets/effects/gargoyle_attic/flooding.png") != null, "Слой протечек загружается")
	_check(load("res://assets/effects/gargoyle_attic/frozen_flooding.png") != null, "Слой замёрзших протечек загружается")
	_check(load("res://assets/portraits/residents/mirabel.png") != null, "Портрет Мирабель загружается")

	var ideal: RefCounted = GargoyleSimulationScript.new()
	var ideal_result: Dictionary = ideal.apply_action(&"liliya", &"animate")
	_check(bool(ideal_result["resolved"]) and ideal.visual_state() == &"awakened", "Оживление даёт идеальный исход")
	_check(int(ideal.get_completion_result()["reputation_change"]) == 1, "Идеальный исход повышает репутацию")
	var repeated_animation: Dictionary = ideal.apply_action(&"nika", &"animate")
	_check(not bool(repeated_animation["applied"]), "Оживлённую горгулью нельзя оживить повторно")
	var late_antimagic: Dictionary = ideal.apply_action(&"felix", &"antimagic")
	_check(bool(late_antimagic["applied"]) and not ideal.is_resolved(), "Антимагия усыпляет оживлённую горгулью")
	_check(ideal.get_completion_result().is_empty(), "После усыпления акт завершения недоступен")
	for cycle in range(4):
		ideal.apply_action(&"nika", &"animate")
		_check(ideal.available_actions().has("antimagic") and ideal.is_resolved(), "После пробуждения доступна антимагия")
		_check("активны" in str(ideal.apply_action(&"felix", &"diagnose")["message"]), "Феликс видит активные чары")
		ideal.apply_action(&"felix", &"antimagic")
		_check(not ideal.is_resolved() and ideal.flooding_state() == &"water", "Повторное усыпление снова нарушает водоотвод")
	ideal.apply_action(&"nika", &"animate")
	_check(ideal.visual_state() == &"awakened" and ideal.flooding_state() == &"none", "Повторное пробуждение восстанавливает водоотвод")
	ideal.world_object["room_frozen"] = true
	var ice_act: Dictionary = ideal.get_completion_result()
	_check("На чердаке остался лёд" in str(ice_act["summary"]) and int(ice_act["reward_adjustment"]) == -30, "Лёд виден в основном акте и уменьшает оплату на 30 монет")
	_check(int(ideal.get_completion_result()["reward_adjustment"]) == -30, "Удержание за лёд не накапливается при повторном расчёте")

	var cleared: RefCounted = GargoyleSimulationScript.new()
	cleared.apply_action(&"nika", &"telekinesis")
	_check(cleared.visual_state() == &"dormant_clean", "Телекинез показывает очищенную пасть")
	_check(not cleared.is_resolved(), "Одна очистка листьев ещё не завершает заявку")
	_check(cleared.flooding_state() == &"water", "После удаления листьев протечки и звук текущей воды сохраняются")
	var clean_repair: Dictionary = cleared.apply_action(&"boris", &"repair")
	var cooperative_result: Dictionary = cleared.get_completion_result()
	_check(bool(clean_repair["resolved"]) and cleared.flooding_state() == &"none", "После очистки Борис полностью восстанавливает водоотвод")
	_check(int(cooperative_result["reward_adjustment"]) == 0 and int(cooperative_result["reputation_change"]) == 1, "Совместная работа Ники и Бориса даёт максимальный результат")
	_check("совместной работой" in str(cooperative_result["consequences"]), "Акт отмечает вклад обоих сотрудников")
	_check("работа вдвоём" in cleared.get_resident_reaction(&"repair"), "Хозяйка замечает совместную работу Ники и Бориса")

	var cleaned_then_animated: RefCounted = GargoyleSimulationScript.new()
	cleaned_then_animated.apply_action(&"nika", &"telekinesis")
	var clean_animation: Dictionary = cleaned_then_animated.apply_action(&"nika", &"animate")
	_check("выплюнула засор" not in str(clean_animation["message"]) and "уже очищенную" in str(clean_animation["message"]), "Оживление очищенной горгульи не возвращает листья в описание результата")

	var temperature_route: RefCounted = GargoyleSimulationScript.new()
	var blocked_ice := GargoyleSimulationScript.new()
	blocked_ice.apply_action(&"liliya", &"freeze")
	var refused: Dictionary = blocked_ice.apply_action(&"boris", &"repair")
	_check(not bool(refused["applied"]) and bool(blocked_ice.world_object["frozen"]) and bool(blocked_ice.world_object["clogged"]) and not bool(blocked_ice.world_object["bypass_open"]), "Борис отказывается от ремонта ледяной пробки и не удаляет лёд или листья")
	_check(preload("res://scripts/employee_reaction_resolver.gd").refusal_pools["frozen_repair"].has(str(refused["message"])), "Борис использует общий отказ от ремонта замёрзшего объекта")
	var hud_contract = load("res://scripts/repair_hud.gd").new()
	hud_contract.last_spoken_employee_message = "Льда нет. Нагрев не восстановит водоотвод."
	_check(hud_contract.result_repeats_employee_message("Льда нет. Нагрев не восстановит водоотвод!"), "Общий HUD подавляет повтор сказанной реплики независимо от пунктуации")
	_check(not hud_contract.result_repeats_employee_message("Камень получил повреждения."), "Новые последствия не скрываются общим правилом")
	hud_contract.last_spoken_employee_message = ""
	_check(not hud_contract.result_repeats_employee_message("Льда нет. Нагрев не восстановит водоотвод."), "Без озвученной реплики результат остаётся доступным")
	hud_contract.free()
	temperature_route.apply_action(&"nika", &"telekinesis")
	temperature_route.apply_action(&"liliya", &"freeze")
	_check(temperature_route.visual_state() == &"frozen" and temperature_route.flooding_state() == &"frozen", "Заморозка включает оба ледяных ассета")
	temperature_route.apply_action(&"liliya", &"heat")
	_check(temperature_route.visual_state() == &"dormant_clean" and temperature_route.flooding_state() == &"water", "Нагрев возвращает обычные протечки")

	var technical: RefCounted = GargoyleSimulationScript.new()
	technical.apply_action(&"boris", &"repair")
	var technical_result: Dictionary = technical.get_completion_result()
	_check(technical.is_resolved() and int(technical_result["reward_adjustment"]) < 0, "Механический обход завершает заявку с меньшей оплатой")
	technical.apply_action(&"nika", &"telekinesis")
	var cleaned_after_bypass: Dictionary = technical.get_completion_result()
	_check(int(cleaned_after_bypass["reward_adjustment"]) == 0 and int(cleaned_after_bypass["reputation_change"]) == 1, "Очистка после открытия обхода улучшает результат до максимального")
	technical.apply_action(&"nika", &"animate")
	var improved_result: Dictionary = technical.get_completion_result()
	_check(int(improved_result["reward_adjustment"]) == 0 and int(improved_result["reputation_change"]) == 1, "Оживление после обходного канала оплачивается как лучший исход")
	_check("пробуждена" in str(improved_result["summary"]), "Итог после улучшения описывает работающую горгулью")

	var damaged: RefCounted = GargoyleSimulationScript.new()
	damaged.apply_action(&"grog", &"physical_move")
	var damaged_result: Dictionary = damaged.get_completion_result()
	_check(damaged.visual_state() == &"damaged", "Силовое воздействие включает повреждённый вид")
	_check(int(damaged_result["compensation_cost"]) > 0 and int(damaged_result["reputation_change"]) < 0, "Повреждение приводит к компенсации и потере репутации")
	_check(bool(damaged_result.get("forfeit_payment", false)), "За сломанную горгулью служба не получает оплату")
	var repeated_force: Dictionary = damaged.apply_action(&"grog", &"physical_move")
	_check(not bool(repeated_force["applied"]) and int(damaged.world_object["damage"]) == 8, "Повторный силовой удар по повреждённой горгулье запрещён")
	var failed_animation: Dictionary = damaged.apply_action(&"liliya", &"animate")
	_check(not bool(failed_animation["applied"]), "Повреждённую горгулью нельзя оживить")
	var failed_repair: Dictionary = damaged.apply_action(&"boris", &"repair")
	_check(not bool(failed_repair["applied"]) and "пролом" in str(failed_repair["message"]), "Борис сообщает, что вода уже уходит через пролом")

	var cleaned_then_damaged: RefCounted = GargoyleSimulationScript.new()
	cleaned_then_damaged.apply_action(&"nika", &"telekinesis")
	cleaned_then_damaged.apply_action(&"grog", &"physical_move")
	_check(cleaned_then_damaged.visual_state() == &"damaged_clean", "После удаления листьев силовое воздействие включает повреждённый вид с чистой пастью")
	var restored_clean_damage: RefCounted = GargoyleSimulationScript.new()
	restored_clean_damage.load_state(cleaned_then_damaged.get_state())
	_check(restored_clean_damage.visual_state() == &"damaged_clean", "Повреждённый вид с чистой пастью восстанавливается из сохранения")
	_check(bool(damaged.action_log.front()["result"].get("caused_damage", false)), "Силовой ущерб записывается общим контрактом")
	_check("Каменный корпус расколот" in str(damaged.apply_action(&"boris", &"diagnose")["message"]), "Повреждённую горгулью можно осмотреть")
	_check(not cleared.available_actions().has("telekinesis") and cleared.available_actions().has("physical_move"), "После очистки листья не вытаскивают повторно, но силовой пролом остаётся доступным")
	var frozen_damage := GargoyleSimulationScript.new()
	frozen_damage.apply_action(&"liliya", &"freeze")
	_check(bool(frozen_damage.action_log.back()["result"].get("caused_damage", false)), "Давление льда запоминается как ущерб Лилии")
	frozen_damage.apply_action(&"felix", &"animate")
	_check("ущерба не зафиксировано" not in str(frozen_damage.get_completion_result()["consequences"]), "Оживление не скрывает предыдущий ущерб льдом в акте")
	var memory := preload("res://scripts/world_memory.gd").new()
	memory.reset()
	memory.ensure_job_context(&"sleeping_gargoyle", {}, "tower_street_8.attic.drain_gargoyle", {"resident_id": "mirabel"})
	memory.record_job_state(&"sleeping_gargoyle", damaged.get_state(), 3, 600)
	_check(str(memory.get_relation("mirabel", "grog").get("access_status", "")) == "warned", "Мирабель помнит повреждение Грогом, но не путает его с уничтожением")
	var attic := attic_scene.instantiate()
	_check(attic != null, "Контроллер чердака компилируется")
	attic.free()
	var save_path := "res://tests/.gargoyle_migration_test.json"
	game_state.selected_job_id = &"sleeping_gargoyle"
	game_state.active_job_id = &"sleeping_gargoyle"
	game_state.jobs[&"sleeping_gargoyle"]["assigned"] = PackedStringArray(["boris"])
	game_state.jobs[&"sleeping_gargoyle"]["dispatched"] = true
	game_state.set_job_repair_state(&"sleeping_gargoyle", temperature_route.get_state())
	_check(game_state._save_to_path(save_path) == OK, "Состояние горгульи сохраняется")
	_check(game_state._load_from_path(save_path) == OK and game_state.active_job_id == &"sleeping_gargoyle", "Активная заявка с горгульей восстанавливается")
	var old_data: Dictionary = JSON.parse_string(FileAccess.get_file_as_string(save_path))
	old_data["version"] = 28
	old_data["generated_jobs"].erase("sleeping_gargoyle")
	var old_file := FileAccess.open(save_path, FileAccess.WRITE)
	old_file.store_string(JSON.stringify(old_data))
	old_file.close()
	_check(game_state._load_from_path(save_path) == OK and bool(game_state.jobs[&"sleeping_gargoyle"].get("generated", false)), "Старая активная заявка безопасно подключается к новому каталогу")
	_check(game_state.active_job_id == &"sleeping_gargoyle" and game_state.jobs[&"sleeping_gargoyle"]["assigned"].has("boris"), "Миграция сохраняет выезд и состав бригады")
	var migrated := GargoyleSimulationScript.new()
	migrated.load_state(game_state.get_job_repair_state(&"sleeping_gargoyle"))
	_check(not migrated.world_object["clogged"] and migrated.world_object["damage"] == 1, "Миграция не возвращает листья и не удаляет повреждение льдом")
	DirAccess.remove_absolute(ProjectSettings.globalize_path(save_path))
	var mixed := GargoyleSimulationScript.new()
	_check(mixed.available_actions().has("heat") and mixed.available_actions().has("freeze"), "Лилия сразу может выбрать огонь или заморозку")
	mixed.apply_action(&"liliya", &"heat")
	_check(int(mixed.world_object["damage"]) == 0, "Нагрев без льда не создаёт выдуманный ущерб")
	mixed.apply_action(&"liliya", &"freeze")
	mixed.apply_action(&"liliya", &"heat")
	mixed.apply_action(&"nika", &"telekinesis")
	_check("Засора больше нет" in str(mixed.apply_action(&"nika", &"diagnose")["message"]) or not str(mixed.get_employee_reaction(&"nika", &"diagnose")).is_empty(), "У Ники есть собственные реплики осмотра")
	mixed.apply_action(&"boris", &"repair")
	var mixed_report: Dictionary = mixed.get_completion_result()
	_check("повреждения после заморозки" in str(mixed_report["summary"]), "Повреждение прямо указано в итоге акта")
	mixed_report.merge({"resident_id": "mirabel", "job_id": "mixed_damage_test", "rating": 3, "crew_ids": ["boris", "nika", "liliya", "grog"], "damage_employee_ids": ["liliya"]}, true)
	memory.reset()
	memory.evaluate_crew_relations(mixed_report)
	_check(int(memory.get_relation("mirabel", "boris").get("professional_trust", 0)) == 10 and int(memory.get_relation("mirabel", "nika").get("professional_trust", 0)) == 10, "Полезная работа Бориса и Ники запоминается отдельно от ущерба Лилии")
	_check(int(memory.get_relation("mirabel", "liliya").get("professional_trust", 0)) == -15 and not memory.resident_relations["mirabel"].has("grog"), "Виновник получает недоверие, простое присутствие не даёт доверия")
	var clean_team := GargoyleSimulationScript.new()
	clean_team.apply_action(&"nika", &"telekinesis")
	clean_team.apply_action(&"boris", &"repair")
	var clean_report: Dictionary = clean_team.get_completion_result()
	clean_report.merge({"resident_id": "mirabel", "job_id": "clean_team_test", "rating": 5, "crew_ids": ["boris", "nika", "grog"]}, true)
	memory.reset()
	memory.evaluate_crew_relations(clean_report)
	_check(int(memory.get_relation("mirabel", "boris").get("professional_trust", 0)) == 10 and not memory.resident_relations["mirabel"].has("grog"), "Доверие начисляется один раз и только участвовавшим в решении")
	var menu = load("res://scenes/ui/ToolBar.tscn").instantiate()
	root.add_child(menu)
	var menu_sim := GargoyleSimulationScript.new()
	game_state.set_job_repair_state(&"sleeping_gargoyle", menu_sim.get_state())
	menu.configure_for_employee(str(game_state.employees[&"boris"]["name"]), PackedStringArray(["diagnose", "repair"]), "")
	menu.show_for_object("Водосточная горгулья", Vector2.ZERO, {}, [{"id": &"test_action", "label": "Работа"}])
	_check(menu.get_node("%DiagnoseButton").visible and not menu.get_node("%RepairButton").visible and menu.temporary_buttons.is_empty(), "До осмотра Борису доступны только осмотр, без дополнительных действий")
	menu._on_button_pressed(menu.get_node("%DiagnoseButton"))
	menu_sim.apply_action(&"boris", &"diagnose")
	game_state.set_job_repair_state(&"sleeping_gargoyle", menu_sim.get_state())
	menu.show_for_object("Водосточная горгулья", Vector2.ZERO)
	_check(menu.get_node("%RepairButton").visible, "Завершённый осмотр открывает работу Бориса")
	menu.show_for_object("Другой объект", Vector2.ZERO)
	_check(not menu.get_node("%RepairButton").visible, "Осмотр одного объекта не открывает работу на другом")
	menu_sim.apply_action(&"liliya", &"freeze")
	game_state.set_job_repair_state(&"sleeping_gargoyle", menu_sim.get_state())
	_check(game_state.get_job_repair_state(&"sleeping_gargoyle").get("boris_inspected_objects", []).has("Водосточная горгулья"), "Изменение состояния не стирает факт осмотра")
	_check(game_state._save_to_path(save_path) == OK and game_state._load_from_path(save_path) == OK and game_state.get_job_repair_state(&"sleeping_gargoyle").get("boris_inspected_objects", []).has("Водосточная горгулья"), "Осмотр сохраняется после загрузки")
	DirAccess.remove_absolute(ProjectSettings.globalize_path(save_path))
	menu.free()
	var refusals := preload("res://scripts/employee_reaction_resolver.gd")
	var rules := preload("res://scripts/object_interaction_rules.gd")
	var frozen_refusal := GargoyleSimulationScript.new()
	frozen_refusal.apply_action(&"liliya", &"freeze")
	var frozen_before: Dictionary = frozen_refusal.world_object.duplicate(true)
	var force_refusal: Dictionary = frozen_refusal.apply_action(&"grog", &"physical_move")
	_check(not bool(force_refusal["applied"]) and frozen_refusal.world_object == frozen_before and refusals.refusal_pools["frozen_force"].has(str(force_refusal["message"])), "Замороженная горгулья отказывает силовой работе без изменения объекта")
	var magic_refusal: Dictionary = frozen_refusal.apply_action(&"nika", &"antimagic")
	_check(not bool(magic_refusal["applied"]) and frozen_refusal.world_object == frozen_before and refusals.refusal_pools["ordinary_ice"].has(str(magic_refusal["message"])), "Антимагический отказ доступен любому сотруднику, не только Феликсу")
	var cold_source: Dictionary = frozen_before.duplicate(true)
	cold_source["cold_source_active"] = true
	_check(rules.refusal_reason(&"antimagic", cold_source).is_empty(), "Антимагия не запрещена при активном источнике холода")
	_check(rules.refusal_reason(&"physical_move", {"frozen": true}).is_empty(), "Один лишь лёд не запрещает силовую работу на объектах, допускающих её")
	var first_refusal: String = refusals.refusal_for(&"frozen_force")
	_check(first_refusal != refusals.refusal_for(&"frozen_force"), "Пул не повторяет подряд одну отказную фразу")
	game_state.set_job_repair_state(&"sleeping_gargoyle", frozen_refusal.get_state())
	var refusal_room = load("res://scenes/GargoyleAttic.tscn").instantiate()
	root.add_child(refusal_room)
	var signals_seen := [0]
	refusal_room.tool_bar.tool_selected.connect(func(_id: StringName) -> void: signals_seen[0] += 1)
	refusal_room.tool_bar.configure_for_employee(str(game_state.employees[&"grog"]["name"]), PackedStringArray(["physical_move"]), "")
	refusal_room.tool_bar.show_for_object("Водосточная горгулья", Vector2.ZERO)
	refusal_room.tool_bar._on_button_pressed(refusal_room.tool_bar.get_node("%PhysicalMoveButton"))
	_check(signals_seen[0] == 0 and not refusal_room.action_in_progress and not refusal_room.repair_hud.is_timed_action_active(), "Отказ в меню не запускает подход, удар или таймер")
	refusal_room.tool_bar.configure_for_employee(str(game_state.employees[&"nika"]["name"]), PackedStringArray(["antimagic"]), "")
	refusal_room.tool_bar.show_for_object("Водосточная горгулья", Vector2.ZERO)
	refusal_room.tool_bar._on_button_pressed(refusal_room.tool_bar.get_node("%AntimagicButton"))
	_check(signals_seen[0] == 0 and not refusal_room.action_in_progress, "Другой сотрудник с антимагией использует тот же отказ без применения магии")
	refusal_room.selected_employee_id = &"boris"
	refusal_room._on_gargoyle_selected()
	_check(refusal_room.tool_bar.get_node("%RepairButton").visible, "После осмотра замороженной горгульи ремонт остаётся доступным для отказа Бориса")
	refusal_room.tool_bar._on_button_pressed(refusal_room.tool_bar.get_node("%RepairButton"))
	_check(signals_seen[0] == 0 and not refusal_room.action_in_progress, "Борис произносит отказ, не начинает ремонт и не убирает лёд")
	refusal_room.simulation.world_object["magic_level"] = 0
	refusal_room.selected_employee_id = &"felix"
	refusal_room._on_gargoyle_selected()
	_check(refusal_room.tool_bar.get_node("%AntimagicButton").visible, "На замороженном объекте антимагия доступна для отказа даже без оставшихся чар")
	refusal_room.simulation.world_object["frozen"] = false
	refusal_room._on_gargoyle_selected()
	_check(refusal_room.tool_bar.temporary_buttons.size() == 1 and refusal_room.tool_bar.temporary_buttons[0].text == "Осмотр", "После подавления чар и оттаивания у Феликса есть осмотр, а не пустое меню")
	_check("чары погашены" in str(refusal_room.simulation.apply_action(&"felix", &"diagnose")["message"]), "Осмотр Феликса объясняет отсутствие оставшейся магической работы")
	var liliya_variants := GargoyleSimulationScript.new()
	var previous_freeze := ""
	var previous_heat := ""
	for iteration: int in 6:
		var freeze_intro := liliya_variants.get_employee_reaction(&"liliya", &"freeze")
		_check(freeze_intro != previous_freeze, "Лилия не повторяет соседние реплики заморозки")
		previous_freeze = freeze_intro
		liliya_variants.apply_action(&"liliya", &"freeze")
		var heat_intro := liliya_variants.get_employee_reaction(&"liliya", &"heat")
		_check(heat_intro != previous_heat, "Лилия не повторяет соседние реплики оттаивания")
		previous_heat = heat_intro
		liliya_variants.apply_action(&"liliya", &"heat")
	var no_ice_intro := liliya_variants.get_employee_reaction(&"liliya", &"heat")
	_check(str(liliya_variants.apply_action(&"liliya", &"heat")["message"]) == no_ice_intro, "Нагрев без льда не дублирует выбранную реплику другим результатом")
	refusal_room.free()
	var ice_spit := GargoyleSimulationScript.new()
	ice_spit.apply_action(&"liliya", &"freeze")
	var ice_animation: Dictionary = ice_spit.apply_action(&"nika", &"animate")
	_check(not bool(ice_spit.world_object["frozen"]) and bool(ice_spit.world_object["room_frozen"]) and ice_spit.is_resolved(), "Оживление очищает горгулью от льда, но не размораживает чердак")
	_check("выплюнула лёд" in str(ice_animation["message"]) and "чердаке остался лёд" in str(ice_spit.get_completion_result()["consequences"]), "Результат оживления и акт различают пробку и оставшийся лёд")
	var ice_loaded := GargoyleSimulationScript.new()
	ice_loaded.load_state(ice_spit.get_state())
	_check(bool(ice_loaded.world_object["room_frozen"]), "Оставшийся на чердаке лёд сохраняется при загрузке")
	var old_ice_state: Dictionary = ice_spit.get_state()
	old_ice_state["world_object"].erase("room_frozen")
	ice_loaded.load_state(old_ice_state)
	_check(bool(ice_loaded.world_object["room_frozen"]), "Старое сохранение восстанавливает лёд по истории заморозки")
	game_state.set_job_repair_state(&"sleeping_gargoyle", ice_spit.get_state())
	var ice_room = load("res://scenes/GargoyleAttic.tscn").instantiate()
	root.add_child(ice_room)
	_check(ice_room.frozen_flooding.visible and not ice_room.flooding.visible and not ice_room.get_node("GargoylePlacement/Frozen").visible, "После оживления ледяной слой комнаты виден, а замороженная горгулья и вода скрыты")
	ice_room.simulation = GargoyleSimulationScript.new()
	ice_room.selected_employee_id = &"grog"
	ice_room._on_gargoyle_selected()
	_check(ice_room.tool_bar.get_node("%PhysicalMoveButton").visible and ice_room.tool_bar.get_node("%PhysicalMoveButton").text == "Выбить засор силой", "Грог видит силовое удаление засора на незамороженной горгулье")
	ice_room.simulation.apply_action(&"nika", &"telekinesis")
	ice_room._on_gargoyle_selected()
	_check(ice_room.tool_bar.get_node("%PhysicalMoveButton").visible and ice_room.tool_bar.get_node("%PhysicalMoveButton").text == "Проломить водосток", "После удаления листьев у Грога остаётся силовой вариант с честным названием")
	ice_room.simulation.apply_action(&"liliya", &"freeze")
	ice_room._on_gargoyle_selected()
	_check(ice_room.tool_bar.get_node("%PhysicalMoveButton").visible and not bool(ice_room.simulation.apply_action(&"grog", &"physical_move")["applied"]), "При заморозке силовая кнопка остаётся для отказа, но удар не выполняется")
	ice_room.free()
	_finish()


func _check(condition: bool, message: String) -> void:
	if condition:
		print("PASS: ", message)
	else:
		failures.append(message)
		push_error("FAIL: %s" % message)


func _finish() -> void:
	if failures.is_empty():
		print("GARGOYLE JOB SMOKE TEST: PASS")
		quit(0)
	else:
		print("GARGOYLE JOB SMOKE TEST: FAIL (%d)" % failures.size())
		quit(1)
