extends SceneTree

const Mirror := preload("res://scripts/portal_mirror_simulation.gd")
const Rules := preload("res://scripts/object_interaction_rules.gd")
var failures: Array[String] = []

func _initialize() -> void:
	call_deferred("_run")

func check(value: bool, message: String) -> void:
	if not value:
		failures.append(message)
		push_error(message)
	else:
		print("PASS: ", message)

func _run() -> void:
	if not "MirrorTests" in OS.get_user_data_dir():
		push_error("Требуется отдельный тестовый профиль")
		quit(1)
		return
	check(true, "Тест использует отдельные сохранения")
	var state := root.get_node("GameState")
	state.start_new_game()
	var mirror := Mirror.new()
	mirror.initialize_from_job(state.jobs[&"portal_mirror"])
	check(not mirror.is_resolved() and mirror.get_completion_result().is_empty(), "Открытый портал нельзя завершить")
	check(mirror.available_actions(&"boris") == PackedStringArray(["diagnose"]), "Борис начинает с осмотра")
	mirror.apply_action(&"boris", &"diagnose")
	check(mirror.available_actions(&"boris").has("cover"), "Осмотр открывает работу Бориса")
	check(not mirror.apply_action(&"boris", &"cover", false)["applied"], "Отсутствие полотна не меняет зеркало")
	check(not mirror.apply_action(&"nika", &"telekinesis")["applied"], "Закреплённое зеркало не перемещается")
	var heat := mirror.apply_action(&"liliya", &"heat")
	check(heat["applied"] and not heat["caused_damage"] and not mirror.world_object["cold_aura"], "Первый нагрев полезен без ущерба")
	check(not "излучает холод" in str(mirror.apply_action(&"boris", &"diagnose")["message"]), "Осмотр после нагрева не придумывает прежний холод")
	check(mirror.apply_action(&"liliya", &"heat")["caused_damage"], "Повторный нагрев фиксирует виновника")
	check(not mirror.apply_action(&"liliya", &"heat")["caused_damage"], "Повторение не создаёт новый ущерб")
	check("деформирована" in str(mirror.apply_action(&"boris", &"diagnose")["message"]), "Осмотр видит повреждение рамы")
	mirror.apply_action(&"boris", &"cover")
	check(mirror.is_resolved() and mirror.visual_state() == &"covered_heat_damaged", "Полотно даёт временное завершение с повреждением")
	check(not mirror.apply_action(&"felix", &"antimagic")["applied"], "Антимагия отказывает через полотно")
	check(mirror.available_actions(&"felix").has("antimagic"), "Отказная кнопка остаётся доступной")
	var temporary := mirror.get_completion_result()
	check(temporary["reward_adjustment"] == -430 and temporary["expense_reimbursement"] == 50, "Согласованная оплата временной изоляции сохранена")
	check(temporary["successful_employee_ids"].has("boris") and temporary["successful_employee_ids"].has("liliya"), "Полезная работа учитывается отдельно от ущерба")
	mirror.apply_action(&"boris", &"uncover")
	check(not mirror.is_resolved(), "Снятие полотна возвращает незавершённое состояние")
	mirror.apply_action(&"felix", &"antimagic")
	check(mirror.visual_state() == &"closed_heat_damaged" and mirror.get_completion_result()["reward_adjustment"] == -350, "Закрытие сохраняет ущерб и удержание")
	check(mirror.available_actions(&"felix").has("antimagic"), "Повторное закрытие остаётся отказным действием")
	var copy := Mirror.new()
	copy.load_state(JSON.parse_string(JSON.stringify(mirror.get_state())))
	check(copy.visual_state() == mirror.visual_state() and copy.is_resolved(), "Состояние проходит JSON сохранение и загрузку")
	check(copy.available_actions(&"boris").has("cover"), "Осмотр сохраняется после загрузки")
	var legacy := Mirror.new()
	legacy.load_state({"world_object": {"portal_open": false, "damage": 1, "cold_aura": false}, "action_log": [{"employee_id": "liliya", "action_id": "heat", "result": {"applied": true, "message": "Повторный нагрев расшатал портал. Рама зеркала начала деформироваться."}}, {"employee_id": "boris", "action_id": "diagnose", "result": {"applied": true}}]})
	check(legacy.action_log[0]["result"]["caused_damage"], "Старое сохранение восстанавливает виновника деформации")
	check(legacy.available_actions(&"boris").has("cover") and legacy.visual_state() == &"closed_heat_damaged", "Старое сохранение восстанавливает осмотр и вид")
	var broken := Mirror.new()
	broken.apply_action(&"boris", &"cover")
	var smash := broken.apply_action(&"grog", &"physical_move")
	check(smash["caused_damage"] and not smash["destroyed_target_ids"].is_empty(), "Разрушение отмечено общим контрактом ущерба")
	check(broken.visual_state() == &"destroyed" and not broken.world_object["covered"], "Разрушенное зеркало не считается завешенным")
	check(broken.get_completion_result()["forfeit_payment"] and broken.get_completion_result()["compensation_cost"] == 300, "Разрушение лишает оплаты и требует прежнюю компенсацию")
	check(not broken.get_completion_result().has("follow_up"), "Разрушенный портал не создаёт призрака из полотна")
	state.active_job_id = &"portal_mirror"
	state.jobs[&"portal_mirror"]["assigned"] = PackedStringArray(["boris", "liliya", "felix"])
	state.set_job_repair_state(&"portal_mirror", mirror.get_state())
	check(state.world_memory.objects.has("portal_mirror_room.portal_mirror"), "Зеркало подключено к общей памяти объектов")
	check(state.complete_active_job(mirror.get_completion_result()), "Завершение принимает фактический результат")
	var report: Dictionary = state.job_reports.back()
	check(report["damage_employee_ids"].has("liliya") and not report["damage_employee_ids"].has("boris"), "Акт отличает виновника от помощника")
	check(report["successful_employee_ids"].has("felix"), "Акт учитывает специалиста, закрывшего портал")
	state.start_new_game()
	state.active_job_id = &"portal_mirror"
	state.jobs[&"portal_mirror"]["assigned"] = PackedStringArray(["boris"])
	state.employees[&"boris"]["arrival_until"] = 0
	state.jobs[&"portal_mirror"]["unlocked"] = true
	state.jobs[&"portal_mirror"]["dispatched"] = true
	state.skip_tutorial()
	state.set_job_repair_state(&"portal_mirror", Mirror.new().get_state())
	check(state.start_job_action(&"portal_mirror", &"boris", &"diagnose", &"", 3), "Незавершённая работа регистрируется общей системой")
	check(state._save_to_path("user://mirror_test.json") == OK, "Тестовое сохранение записывается отдельно")
	check(state._load_from_path("user://mirror_test.json") == OK and not state.get_pending_job_action(&"portal_mirror").is_empty(), "Сохранение восстанавливает незавершённую работу")
	var room := (load("res://scenes/PortalMirrorHouse.tscn") as PackedScene).instantiate()
	root.add_child(room)
	await process_frame
	check(room.action_in_progress and room.pending_physical_action == &"diagnose", "Сцена возобновляет незавершённую работу")
	room._on_physical_timer_finished(&"diagnose")
	check(room.simulation.world_object["inspected"], "Восстановленная работа применяется после завершения")
	state.clear_pending_job_action(&"portal_mirror")
	state.owned_supply_items.append("protective_cloth")
	room._begin_action(&"cover")
	check(not room.simulation.world_object["covered"] and state.get_pending_job_action(&"portal_mirror").is_empty(), "Подход не меняет объект и не запускает время работы")
	check(not state.get_job_repair_state(&"portal_mirror")["pending_actor_action"].is_empty(), "Подход сохраняется до начала работы")
	room._on_employee_selected(&"liliya")
	check(room.selected_employee_id == &"boris", "Смена выбора не меняет исполнителя уже начатой работы")
	room._on_action_impact(&"cover")
	check(not room.simulation.world_object["covered"] and not state.get_pending_job_action(&"portal_mirror").is_empty(), "После подхода начинается работа без раннего изменения объекта")
	room._on_action_finished()
	check(not room.simulation.world_object["covered"], "Окончание анимации не обгоняет время работы")
	state.clear_pending_job_action(&"portal_mirror")
	room._on_physical_timer_finished(&"cover")
	check(room.simulation.world_object["covered"] and room.simulation.pending_actor_action.is_empty(), "Полотно устанавливается после подхода и завершения работы")
	check(not state.has_supply_item(&"protective_cloth"), "Завершённая установка списывает полотно один раз")
	room.queue_free()
	await process_frame
	print("MIRROR PROPERTIES: ", "PASS" if failures.is_empty() else "FAIL", " (", failures.size(), ")")
	quit(0 if failures.is_empty() else 1)