extends SceneTree

const Simulation := preload("res://scripts/prison_simulation.gd")
const Definition := preload("res://data/prison/prison.tres")

func _initialize() -> void:
	call_deferred("_run")

func _run() -> void:
	var sim := Simulation.new()
	sim.initialize(Definition)
	assert(not sim.available("antimagic"))
	assert(not sim.state["conversation_unlocked"])
	assert(sim.apply("inspect"))
	assert(sim.apply("repair_mechanism"))
	assert(sim.apply("test_protection"))
	assert(sim.state["reverse_feedback"] and sim.state["eye_revealed"])
	assert(not sim.available("authorize_shutdown"))
	assert(sim.apply("stop_test"))
	assert(sim.apply("read_record"))
	assert(sim.apply("authorize_shutdown"))
	assert(sim.apply("antimagic"))
	assert(sim.state["escaped"] and sim.state["mark_received"])
	assert(not sim.available("wait_specialist"))
	assert(sim.apply("finish_repair"))
	var restored := Simulation.new()
	restored.initialize(Definition)
	assert(restored.load_state(sim.get_state()))
	assert(restored.state == sim.state)
	assert(not restored.load_state({"version": 2, "properties": {}}))
	sim.initialize(Definition)
	for id: String in ["inspect", "repair_mechanism", "test_protection", "stop_test", "wait_specialist"]:
		assert(sim.apply(id))
	assert(sim.state["repair_completed"] and not sim.state["escaped"] and not sim.state["mark_received"])
	var gs = preload("res://tests/prison_test_state.gd").install(root)
	gs.prepare_prison(PackedStringArray(["boris", "grog"]))
	var scene := load("res://scenes/PrisonRoom.tscn") as PackedScene
	var room := scene.instantiate()
	root.add_child(room)
	await process_frame
	room._close_conversation()
	assert(room.get_node("Cells").visible)
	assert(not room.get_node("Office").visible)
	room.show_room("cells")
	assert(room.get_node("Cells").visible)
	assert(room.get_node("Cells/Gate").flip_h)
	assert(not room.get_node("Cells/Talk").visible)
	assert(room.get_node("Cells/ArrivalGuard").visible)
	assert(not room.get_node("Office/Guard").visible)
	assert(room.get_node("Cells/LockHotspot").tooltip_text.is_empty())
	room.show_room("office")
	room._open_control_panel()
	assert(room.get_node("ProtectionPanel/Panel/Switch1").disabled)
	assert(not room.get_node("ProtectionPanel/Panel/On1").visible)
	room._close_control_panel()
	room.show_room("cells")
	for id: String in ["inspect", "repair_mechanism"]:
		assert(room.perform_action(id))
		while room.dialogue_open:
			room._next_line()
	assert(room.simulation.state["guard_away"])
	assert(not room.get_node("Cells/ArrivalGuard").visible)
	room._show_actions("lock")
	assert(not room.tool_bar.visible)
	room.show_room("office")
	room._open_control_panel()
	assert(not room.get_node("ProtectionPanel/Panel/Switch1").disabled)
	room.get_node("ProtectionPanel/Panel/Switch1").pressed.emit()
	assert(room.simulation.state["empty_protection_active"])
	assert(room.current_room == "office")
	assert(not room.dialogue_open)
	assert(room.get_node("ProtectionPanel").visible)
	assert(room.get_node("ProtectionPanel/Panel/On1").visible)
	assert(room.get_node("ProtectionPanel").current_action == "stop_test")
	room._close_control_panel()
	room.show_room("cells")
	assert(room.dialogue_open)
	assert(room.get_node("Cells/MysteriousGirlPain").visible)
	assert(not room.get_node("Cells/Talk").visible)
	while room.dialogue_open:
		room._next_line()
	assert(room.current_room == "cells")
	room.show_room("office")
	room._open_control_panel()
	room.get_node("ProtectionPanel/Panel/Switch1").pressed.emit()
	assert(not room.simulation.state["empty_protection_active"])
	assert(room.current_room == "office")
	assert(not room.dialogue_open)
	assert(room.get_node("ProtectionPanel").visible)
	assert(room.simulation.state["stop_dialogue_pending"])
	room._close_control_panel()
	room.show_room("cells")
	assert(room.dialogue_open and room.dialogue_section == "stop_test")
	room._close_conversation()
	assert(room.get_node("Cells/ArrivalGuard").visible)
	assert(room.get_node("Cells/Talk").visible)
	room._open_conversation()
	assert(room.get_node("Portrait").visible)
	assert(not room.perform_action("stop_test"))
	room._close_conversation()
	room.show_room("office")
	assert(room.simulation.state["pain_seen"])
	room.queue_free()
	print("PRISON SCENE: PASS")
	quit()
